{% set data = load_setup_py_data() %}

package:
  name: pynisher
  version: {{ data['version'] }}

source:
  path: ..

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python >=3.4,{{PY_VER}}*
    - setuptools
  run:
    - python {{PY_VER}}*
    - numpy >=1.8*
